name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Rust toolchain specified in rust-toolchain.toml
      run: rustup toolchain install nightly && rustup default nightly && rustup target add wasm32-unknown-unknown

    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.1'

    - name: Install daisyui
      run: npm i -D daisyui@latest

    - name: Install tailwind typography
      run: npm install -D @tailwindcss/typography

    - name: Install cargo-leptos
      run: cargo install --locked cargo-leptos

    - name: Compile Leptos
      run: RUSTFLAGS=--cfg=web_sys_unstable_apis cargo leptos build --release

    - name: Prepare release package
      run: |
        mkdir release_package
        cp -r target/site release_package/
        cp target/release/delphinus release_package/
        cp -r dictionaries release_package/
        cd release_package
        zip -r release_package.zip .
      shell: bash

    - name: Create package
      uses: actions/create-release@v1
      id: create_release
      with:
        tag_name: ${{ github.event.release.tag_name }}
        release_name: ${{ github.event.release.name }}
        draft: false
        prerelease: false

    - name: Upload package
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release_package/release_package.zip
        asset_name: ${{ github.event.release.name }}.zip
        asset_content_type: application/zip
